name: Build and Push MariaDB Docker Images
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Filter paths with changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            mariadb: mariadb/**
  build:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        mariadb: ${{ fromJSON(needs.changes.outputs.images) }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build MariaDB
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.mariadb }}
          file: ${{ matrix.mariadb }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: besteadfast/stallion-mariadb:latest
