name: MariaDB Images
on:
  push:
    branches:
      - main
    paths:
      - mariadb/**
      - .github/workflows/mariadb-images.yml
      - .github/workflows/generic.yml
  workflow_dispatch:
jobs:
  generic:
    uses: ./.github/workflows/generic.yml
    with:
      image-name: 'mariadb'
      latest: '10'
      filters: |
        mariadb-10:
          - mariadb/10/**
          - .github/workflows/mariadb-images.yml
          - .github/workflows/generic.yml
    secrets: inherit