name: NGINX Images
on:
  push:
    branches:
      - main
    paths:
      - nginx/**
      - .github/workflows/nginx-images.yml
      - .github/workflows/generic.yml
  workflow_dispatch:
jobs:
  generic:
    uses: ./.github/workflows/generic.yml
    with:
      image-name: 'nginx'
      latest: '1'
      filters: |
        nginx-1:
          - nginx/1/**
          - .github/workflows/nginx-images.yml
          - .github/workflows/generic.yml
    secrets: inherit
