name: Node Images
on:
  push:
    branches:
      - main
    paths:
      - node/**
      - .github/workflows/node-images.yml
      - .github/workflows/generic.yml
  workflow_dispatch:
jobs:
  generic:
    uses: ./.github/workflows/generic.yml
    with:
      image-name: 'node'
      latest: '12'
      filters: |
        node-10:
          - node/10/**
          - .github/workflows/node-images.yml
          - .github/workflows/generic.yml
        node-12:
          - node/12/**
          - .github/workflows/node-images.yml
          - .github/workflows/generic.yml
    secrets: inherit
