name: PHP Images
on:
  push:
    branches:
      - main
    paths:
      - php/**
      - .github/workflows/php-images.yml
      - .github/workflows/generic.yml
  workflow_dispatch:
jobs:
  generic:
    uses: ./.github/workflows/generic.yml
    with:
      image-name: 'php'
      latest: '8.0'
      filters: |
        php-7.4:
          - php/7.4/**
          - .github/workflows/php-images.yml
          - .github/workflows/generic.yml
        php-8.0:
          - php/8.0/**
          - .github/workflows/php-images.yml
          - .github/workflows/generic.yml
    secrets: inherit
